version: 0.2

# AWS CodeBuild buildspec para CI/CD
# Este arquivo é usado pelo AWS CodeBuild para fazer build e deploy automático

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    ECR_REPO_NAME: "usuarios-api"
    DOTNET_VERSION: "8.0"
  parameter-store:
    DB_CONNECTION_STRING: "/usuarios/db-connection-string"
    JWT_KEY: "/usuarios/jwt-key"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo "Building image with tag $IMAGE_TAG"
      
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $ECR_REPO_NAME:$IMAGE_TAG .
      - docker tag $ECR_REPO_NAME:$IMAGE_TAG $ECR_URI:$IMAGE_TAG
      - docker tag $ECR_REPO_NAME:$IMAGE_TAG $ECR_URI:latest
      
  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $ECR_URI:$IMAGE_TAG
      - docker push $ECR_URI:latest
      - echo "Build completed successfully"
      - printf '[{"name":"usuarios-api","imageUri":"%s"}]' $ECR_URI:$IMAGE_TAG > imagedefinitions.json
      - echo "Image URI - $ECR_URI:$IMAGE_TAG"

artifacts:
  files:
    - imagedefinitions.json
    
cache:
  paths:
    - '/root/.nuget/**/*'
    - '/root/.dotnet/**/*'
